replicas: 2
deploymentName: trainers
containers:
  - image: docker.io/brunoanjos/trainers:latest
    command: [ "sh", "-c", "./executable -l -d -a" ]
    ports:
      - containerPort: 8009
    env:
      - name: MONGODB_URL
        value: "mongodb://novapokemon-trainersdb:27017"
      - name: HEADLESS_SERVICE_NAME
        value: "$instance"
static: False
depthFactor: 1
instanceNameFmt: [ "$DEPLOYMENT_NAME", "-", "$REPLICA_NUM"]